---
- name: Grafana
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - /etc/ansible/alloy_vars.yml

  pre_tasks:
    - name: Update repositories
      ansible.builtin.apt:
        # Do not update the cache on every run to avoid conflicts with landscape client
        update_cache: false
      # Choosing to run the tasks only when changes have been made in the Git repository
      # changed_when: false

  tasks:
    - name: Copy required files
      ansible.builtin.include_tasks: tasks/files.yml
    - name: Packages
      ansible.builtin.include_tasks: tasks/packages.yml
    - name: Grafana
      ansible.builtin.include_tasks: tasks/grafana.yml
